### ISSUE TITLE
xmlns namespace disappears

### ISSUE THREAD

**Issue by krissik** [plone/diazo#59]
Hi all,

I have a theme that has `xmlns` and `xmlns:xlink` namespace declaration

```
<!doctype html>
<html class="start index" lang="de"
      xmlns="http://www.w3.org/1999/xhtml"
      xmlns:xlink="http://www.w3.org/1999/xlink"
      >
<head>
...
```

If I look at the html source code in my browser there is `xmlns="http://www.w3.org/1999/xhtml"` missing:
```
<!DOCTYPE html>
<html xmlns:xlink="http://www.w3.org/1999/xlink" class="start index" lang="de" xml:lang="de">
<head>
...
```

If I remove `xmlns:xlink="http://www.w3.org/1999/xlink"` from the theme the html in browser looks like that:
```
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="de">
  <head>
...
```

I would expect both namespace declarations on the output html. Do I miss something?

**Comment by lrowe** [comment]
XML namespace prefixes are not part of HTML. We're unable to pass them through as attributes as the libxml2 HTMLParser will drop anything after the ':'.

It is possible to use the XMLParser for themes with the diazo rules compiler if you call it from python, but I don't think it's exposed from the command line and I seem to remember there being problems but I forget the details.

It should be possible to construct a diazo rule that will add in your xlink:attr to the theme. Unfortunately any namespaced attributes in the content will have the attribute name stripped as the content is parsed using the HTMLParser.

**Comment by djay** [comment]
There is a similar problem if you want a theme file that outputs XML instead of html. Which seems like a reasonable thing to do and it's unintuitive that its not possible. for example, if you have a theme with an XML declaration, not only will it change the declaration but it will insert html and body tags.

```
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"><body>...
```

There has to be a way, at least for plone, to pass that information outside of the layers so it gets put back in correctly at the end. Maybe via the request?

**Comment by lrowe** [comment]
@djay The HTMLParser parses as HTML so will insert missing tags that HTML requires (similar to the way a browser will.) I suggest experimenting with supplying an XMLParser here: https://github.com/plone/diazo/blob/master/lib/diazo/compiler.py#L89-L90

plone.app.theming changes the doctype using a regex since XSLT is unable to output the non-xmlish '<!DOCTYPE html>'. IIRC it's configurable in plone.app.theming.

**Comment by djay** [comment]
@lrowe yes I see its even more tricky than I thought because you really want to use a different parser per theme file, as a theme doesn't have just one theme file. That would mean an even bigger change to use different parsers based on the theme file. 

If its ok, I'd like to keep it open as its still an open feature request/bug in that from UX point of view it's unexpected that it drops the declaration and it can probably be fixed.

**Comment by lrowe** [comment]
@djay the original bug report about prefixed attributes is a limitation of libxml2 not diazo. You're report about the doctype being replaced happens in plone.app.theming (and I believe it is configurable there.) Keeping this bug report open is not useful as it's not really possible to fix in diazo.

**Comment by lrowe** [comment]
@djay it might be possible to make the parser configurable per theme based on an attribute (see: https://github.com/plone/diazo/blob/master/lib/diazo/rules.py#L109) but you'd need to ensure both HTMLParser and XMLParser instances were passed down into the function as plone.app.theming relies on being able to configure them (see: https://github.com/plone/plone.app.theming/blob/master/src/plone/app/theming/utils.py#L600).

**Comment by lrowe** [comment]
Hmm... #58 suggests that libxml2 is now successfully parsing prefixed attributes so it might not be a complete lost cause. I can't find mention of it in http://xmlsoft.org/news.html though.

**Comment by krissik** [comment]
I do not think that libxml2 is correctly parsing prefixed attributes. I had problems to get nodes with 'xlink:href' attributes that is why I use `local-name()`
```
theme_doc.xpath('//@*[local-name()="xlink:href"]'):
```
to get the attribute and than `getparent()` to get the node and change the url so that it contains absolute prefix. (Better solutions welcome)

#### An addition to my original issue:

My theme contains this:

```
<svg><use xlink:href="img/icons.svg#home"/></svg>
```

If I do not add `xmlns:xlink="http://www.w3.org/1999/xlink"` to it diazo will show this error:

```
...
Tag section invalid [629:72]
Tag footer invalid [695:8]
htmlParseEntityRef: no name [713:73]
Tag nav invalid [716:23]
Tag nav invalid [731:23]
Namespace prefix xlink for href on use is not defined [226:214]
Namespace prefix xlink for href on use is not defined [264:232]
Namespace prefix xlink for href on use is not defined [265:211]
Namespace prefix xlink for href on use is not defined [539:181]
```
The namespace declaration is not needed for browsers (as far as I understood this) 

Just guessing: etree.HTMLParser is not good for parsing html5 themes and html5parser (http://lxml.de/html5parser.html) could be an idea?

**Comment by krissik** [comment]
Sorry, reopened it by accident.
